export interface TemplateElement {
  id: string;
  type: 'text' | 'image' | 'shape';
  content?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize?: number;
  fontWeight?: string;
  color?: string;
  backgroundColor?: string;
  textAlign?: 'left' | 'center' | 'right';
  borderRadius?: number;
  opacity?: number;
  imageUrl?: string;
  objectFit?: 'cover' | 'contain' | 'fill';
}

export interface Template {
  id: string;
  name: string;
  category: 'instagram-post' | 'instagram-story' | 'facebook-post' | 'linkedin-post' | 'flyer';
  width: number;
  height: number;
  thumbnail: string;
  backgroundColor: string;
  elements: TemplateElement[];
}

export const realEstateTemplates: Template[] = [
  {
    id: 't1',
    name: 'Modern Listing - Instagram Post',
    category: 'instagram-post',
    width: 1080,
    height: 1080,
    thumbnail: '',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'e1',
        type: 'image',
        x: 0,
        y: 0,
        width: 1080,
        height: 720,
        imageUrl: '',
        objectFit: 'cover',
      },
      {
        id: 'e2',
        type: 'shape',
        x: 0,
        y: 680,
        width: 1080,
        height: 400,
        backgroundColor: '#1a1a1a',
        opacity: 0.9,
      },
      {
        id: 'e3',
        type: 'text',
        content: 'JUST LISTED',
        x: 60,
        y: 740,
        width: 960,
        height: 60,
        fontSize: 48,
        fontWeight: '700',
        color: '#ffffff',
        textAlign: 'left',
      },
      {
        id: 'e4',
        type: 'text',
        content: '123 Ocean Drive, Miami Beach',
        x: 60,
        y: 810,
        width: 960,
        height: 50,
        fontSize: 32,
        fontWeight: '400',
        color: '#ffffff',
        textAlign: 'left',
      },
      {
        id: 'e5',
        type: 'text',
        content: '$2,500,000',
        x: 60,
        y: 880,
        width: 960,
        height: 80,
        fontSize: 64,
        fontWeight: '700',
        color: '#4ade80',
        textAlign: 'left',
      },
      {
        id: 'e6',
        type: 'text',
        content: '4 Bed • 3 Bath • 3,200 SqFt',
        x: 60,
        y: 980,
        width: 960,
        height: 40,
        fontSize: 28,
        fontWeight: '400',
        color: '#d1d5db',
        textAlign: 'left',
      },
    ],
  },
  {
    id: 't2',
    name: 'Luxury Listing - Instagram Story',
    category: 'instagram-story',
    width: 1080,
    height: 1920,
    thumbnail: '',
    backgroundColor: '#000000',
    elements: [
      {
        id: 'e1',
        type: 'image',
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        imageUrl: '',
        objectFit: 'cover',
        opacity: 0.7,
      },
      {
        id: 'e2',
        type: 'shape',
        x: 60,
        y: 1400,
        width: 960,
        height: 420,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        opacity: 0.95,
      },
      {
        id: 'e3',
        type: 'text',
        content: 'NEW LISTING',
        x: 100,
        y: 1450,
        width: 880,
        height: 50,
        fontSize: 36,
        fontWeight: '600',
        color: '#dc2626',
        textAlign: 'center',
      },
      {
        id: 'e4',
        type: 'text',
        content: '123 Ocean Drive',
        x: 100,
        y: 1520,
        width: 880,
        height: 60,
        fontSize: 48,
        fontWeight: '700',
        color: '#1a1a1a',
        textAlign: 'center',
      },
      {
        id: 'e5',
        type: 'text',
        content: 'Miami Beach, FL',
        x: 100,
        y: 1590,
        width: 880,
        height: 40,
        fontSize: 32,
        fontWeight: '400',
        color: '#6b7280',
        textAlign: 'center',
      },
      {
        id: 'e6',
        type: 'text',
        content: '$2,500,000',
        x: 100,
        y: 1660,
        width: 880,
        height: 70,
        fontSize: 56,
        fontWeight: '700',
        color: '#1a1a1a',
        textAlign: 'center',
      },
      {
        id: 'e7',
        type: 'text',
        content: '4 BD | 3 BA | 3,200 SF',
        x: 100,
        y: 1750,
        width: 880,
        height: 40,
        fontSize: 28,
        fontWeight: '400',
        color: '#6b7280',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 't3',
    name: 'Elegant Listing - Facebook Post',
    category: 'facebook-post',
    width: 1200,
    height: 630,
    thumbnail: '',
    backgroundColor: '#f3f4f6',
    elements: [
      {
        id: 'e1',
        type: 'image',
        x: 0,
        y: 0,
        width: 700,
        height: 630,
        imageUrl: '',
        objectFit: 'cover',
      },
      {
        id: 'e2',
        type: 'shape',
        x: 700,
        y: 0,
        width: 500,
        height: 630,
        backgroundColor: '#1e293b',
      },
      {
        id: 'e3',
        type: 'text',
        content: 'JUST LISTED',
        x: 750,
        y: 100,
        width: 400,
        height: 50,
        fontSize: 40,
        fontWeight: '700',
        color: '#fbbf24',
        textAlign: 'left',
      },
      {
        id: 'e4',
        type: 'text',
        content: '123 Ocean Drive',
        x: 750,
        y: 170,
        width: 400,
        height: 50,
        fontSize: 36,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'left',
      },
      {
        id: 'e5',
        type: 'text',
        content: 'Miami Beach, FL',
        x: 750,
        y: 230,
        width: 400,
        height: 35,
        fontSize: 24,
        fontWeight: '400',
        color: '#cbd5e1',
        textAlign: 'left',
      },
      {
        id: 'e6',
        type: 'text',
        content: '$2,500,000',
        x: 750,
        y: 300,
        width: 400,
        height: 70,
        fontSize: 52,
        fontWeight: '700',
        color: '#4ade80',
        textAlign: 'left',
      },
      {
        id: 'e7',
        type: 'text',
        content: '4 Bedrooms\n3 Bathrooms\n3,200 SqFt',
        x: 750,
        y: 400,
        width: 400,
        height: 120,
        fontSize: 24,
        fontWeight: '400',
        color: '#e2e8f0',
        textAlign: 'left',
      },
    ],
  },
  {
    id: 't4',
    name: 'Minimalist - Instagram Post',
    category: 'instagram-post',
    width: 1080,
    height: 1080,
    thumbnail: '',
    backgroundColor: '#fafafa',
    elements: [
      {
        id: 'e1',
        type: 'image',
        x: 90,
        y: 90,
        width: 900,
        height: 600,
        imageUrl: '',
        objectFit: 'cover',
        borderRadius: 10,
      },
      {
        id: 'e2',
        type: 'text',
        content: 'NEW LISTING',
        x: 90,
        y: 730,
        width: 900,
        height: 40,
        fontSize: 32,
        fontWeight: '600',
        color: '#1a1a1a',
        textAlign: 'left',
      },
      {
        id: 'e3',
        type: 'text',
        content: '123 Ocean Drive, Miami Beach',
        x: 90,
        y: 780,
        width: 900,
        height: 45,
        fontSize: 28,
        fontWeight: '400',
        color: '#6b7280',
        textAlign: 'left',
      },
      {
        id: 'e4',
        type: 'text',
        content: '$2,500,000',
        x: 90,
        y: 840,
        width: 450,
        height: 60,
        fontSize: 48,
        fontWeight: '700',
        color: '#1a1a1a',
        textAlign: 'left',
      },
      {
        id: 'e5',
        type: 'text',
        content: '4 BD • 3 BA • 3,200 SF',
        x: 90,
        y: 920,
        width: 900,
        height: 40,
        fontSize: 24,
        fontWeight: '400',
        color: '#9ca3af',
        textAlign: 'left',
      },
    ],
  },
  {
    id: 't5',
    name: 'Bold - Instagram Post',
    category: 'instagram-post',
    width: 1080,
    height: 1080,
    thumbnail: '',
    backgroundColor: '#dc2626',
    elements: [
      {
        id: 'e1',
        type: 'text',
        content: 'JUST LISTED',
        x: 60,
        y: 80,
        width: 960,
        height: 80,
        fontSize: 64,
        fontWeight: '900',
        color: '#ffffff',
        textAlign: 'center',
      },
      {
        id: 'e2',
        type: 'image',
        x: 90,
        y: 200,
        width: 900,
        height: 500,
        imageUrl: '',
        objectFit: 'cover',
        borderRadius: 15,
      },
      {
        id: 'e3',
        type: 'shape',
        x: 60,
        y: 740,
        width: 960,
        height: 260,
        backgroundColor: '#ffffff',
        borderRadius: 15,
      },
      {
        id: 'e4',
        type: 'text',
        content: '123 Ocean Drive',
        x: 100,
        y: 770,
        width: 880,
        height: 50,
        fontSize: 40,
        fontWeight: '700',
        color: '#1a1a1a',
        textAlign: 'center',
      },
      {
        id: 'e5',
        type: 'text',
        content: 'Miami Beach, FL',
        x: 100,
        y: 830,
        width: 880,
        height: 35,
        fontSize: 28,
        fontWeight: '400',
        color: '#6b7280',
        textAlign: 'center',
      },
      {
        id: 'e6',
        type: 'text',
        content: '$2,500,000',
        x: 100,
        y: 880,
        width: 880,
        height: 60,
        fontSize: 52,
        fontWeight: '700',
        color: '#dc2626',
        textAlign: 'center',
      },
      {
        id: 'e7',
        type: 'text',
        content: '4 Bed • 3 Bath • 3,200 SqFt',
        x: 100,
        y: 950,
        width: 880,
        height: 35,
        fontSize: 24,
        fontWeight: '400',
        color: '#9ca3af',
        textAlign: 'center',
      },
    ],
  },
];
